import type { ReadingMission } from "./types";

export const learningPath = [
  { id: "sounds", name: "Nido de sonidos", focus: "Discriminación de sonidos del habla", icon: "👂" },
  { id: "letters", name: "Bosque de letras", focus: "Relación entre letras y sonidos", icon: "🌳" },
  { id: "syllables", name: "Puente de sílabas", focus: "Combinación de sílabas", icon: "🌉" },
  { id: "words", name: "Laguna de palabras", focus: "Lectura y significado de palabras", icon: "💧" },
  { id: "stories", name: "Cueva de cuentos", focus: "Frases e historias breves", icon: "📖" },
] as const;

export const missions: ReadingMission[] = [
  {
    id: "sounds-minti-01",
    stageId: "sounds",
    area: "Nido de sonidos",
    title: "El eco de Minti",
    icon: "👂",
    targetWord: "MINTI",
    prompt: "¿Qué palabra empieza como MINTI?",
    spokenPrompt: "Escucha: Minti. ¿Qué palabra empieza con el mismo sonido? Mesa, sol o pato.",
    choices: ["MESA", "SOL", "PATO"],
    answer: "MESA",
    hint: "Pista: MINTI y MESA empiezan con mmm.",
    success: "¡Muy bien! MINTI y MESA empiezan igual.",
    retry: "Casi. Escucha el comienzo: mmminti.",
    reward: { id: "echo", name: "Piedra del eco", symbol: "〽", color: 0x4cc9e8, accent: 0xd8f7ff },
  },
  {
    id: "letters-sol-01",
    stageId: "letters",
    area: "Bosque de letras",
    title: "La letra del sol",
    icon: "☀️",
    targetWord: "SOL",
    prompt: "¿Qué letra aparece al principio?",
    spokenPrompt: "Escucha: sol. ¿Qué letra aparece al principio de sol?",
    choices: ["M", "S", "P"],
    answer: "S",
    hint: "Pista: SOL y SOPA empiezan igual.",
    success: "¡Lo encontraste! SOL empieza con S.",
    retry: "Casi. Escucha otra vez: sol.",
    reward: { id: "sun", name: "Piedra del sol", symbol: "☀", color: 0xffd85b, accent: 0xfff2a8 },
  },
  {
    id: "syllables-map-01",
    stageId: "syllables",
    area: "Puente de sílabas",
    title: "El mapa partido",
    icon: "🌉",
    targetWord: "MA + PA",
    prompt: "¿Qué palabra forman estas partes?",
    spokenPrompt: "Une las partes: ma, pa. ¿Qué palabra forman? Mapa, mata o pala.",
    choices: ["MAPA", "MATA", "PALA"],
    answer: "MAPA",
    hint: "Pista: di las dos partes seguidas: MA, PA.",
    success: "¡Eso es! MA y PA forman MAPA.",
    retry: "Casi. Une despacio: ma, pa.",
    reward: { id: "bridge", name: "Piedra del puente", symbol: "⌒", color: 0xff9b72, accent: 0xffd1bd },
  },
  {
    id: "words-sun-01",
    stageId: "words",
    area: "Laguna de palabras",
    title: "El reflejo dorado",
    icon: "💧",
    targetWord: "☀️",
    prompt: "¿Qué palabra nombra el dibujo?",
    spokenPrompt: "Mira el dibujo. ¿Qué palabra lo nombra? Sol, mar o pan.",
    choices: ["SOL", "MAR", "PAN"],
    answer: "SOL",
    hint: "Pista: brilla en el cielo y nos da luz.",
    success: "¡Correcto! El dibujo representa el SOL.",
    retry: "Casi. Mira lo que brilla en el cielo.",
    reward: { id: "lagoon", name: "Piedra de la laguna", symbol: "≈", color: 0x42b8ad, accent: 0xbef2e8 },
  },
  {
    id: "stories-sun-01",
    stageId: "stories",
    area: "Cueva de cuentos",
    title: "La frase escondida",
    icon: "📖",
    targetWord: "MINTI VE EL…",
    prompt: "¿Qué palabra completa la frase?",
    spokenPrompt: "Completa la frase: Minti ve el... sol, pan o mar.",
    choices: ["SOL", "PAN", "MAR"],
    answer: "SOL",
    hint: "Pista: la historia sucede al amanecer.",
    success: "¡Historia completa! Minti ve el SOL.",
    retry: "Casi. Recuerda qué aparece al amanecer.",
    reward: { id: "story", name: "Piedra del cuento", symbol: "✦", color: 0x9b7ede, accent: 0xe4d9ff },
  },
];

export const firstMission = missions[1];

export function getMission(missionId: string): ReadingMission {
  return missions.find((mission) => mission.id === missionId) ?? firstMission;
}
